import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Sawarabi_Gothic } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import "./globals.css";

const sawarabi = Sawarabi_Gothic({
  variable: "--font-sawarabi",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sawarabi.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <ClerkProvider publishableKey="pk_test_Z2l2aW5nLWJlZS01NS5jbGVyay5hY2NvdW50cy5kZXYk">
          {children}
        </ClerkProvider>
      </body>
      <Analytics />
      <SpeedInsights />
    </html>
  );
}