import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Zen_Kaku_Gothic_New } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from "@vercel/speed-insights/next"
import "./globals.css";

const zenKakuGothicNew = Zen_Kaku_Gothic_New({
  variable: "--font-zen-kaku-gothic-new",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${zenKakuGothicNew.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <ClerkProvider
          appearance={{
            theme: 'simple',
            variables: {
              colorPrimary: "#466060",
              colorBackground: "#f0f5f5",
              colorForeground: "#1c2c2c",
              colorMutedForeground: "#586e6e",
              colorInput: "#ffffff",
              colorInputForeground: "#1c2c2c",
              borderRadius: "0.25rem",
              fontFamily: "var(--font-zenKakuGothicNew), sans-serif",
            },
          }}
        >
          {children}
        </ClerkProvider>
      </body>
      <Analytics />
      <SpeedInsights />
    </html>
  );
}